GET http://localhost:3000/api/user/test HTTP/1.1

###
POST http://localhost:3000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "username": "tahayk3",
    "email": "tahayk3@gmail.com",
    "password":"user3PW" 
}

###
POST http://localhost:3000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email": "tahayk3@gmail.com",
    "password":"user3PW" 
}
